package com.cozyisland.CozyIslandtgbot.enums;

public enum InlineMarkupType {
    APPLICATIONS_MENU,
    DONATE_MENU,
    FEEDBACK_MENU,
    FEEDBACK_SHOW,
    FEEDBACK_NEW,
    FEEDBACK_LIST_MENU,
    VOLUNTEER_MENU,
    MAIN_MENU,
    PET_CLAIM_APPLICATION,
    PET_CLAIM_APPLICATION_MENU,
    PETS_MENU,
    RETURN_TO_MENU,
    // TODO
    RETURN_TO_MENU_BACK,
    VOLUNTEER_APPLICATION_MENU,
    PROCEED_MENU,
    YES_NO,
    CANCEL
}
